---
title: "DfE Git Academy"
date: "Last updated: `r Sys.Date()`"
author: "statistics.development@education.gov.uk"
site: "_site.yml"
---

```{r include=FALSE}
library(fontawesome)
library(quarto)
library(yaml)
```

---

Welcome to the DfE's Git Academy. This is a collection of interactive tasks you 
can work through to help learn and practice using Git. As this is intended to be
a practical guide, we provide the 
[git-academy-sandbox](https://github.com/dfe-analytical-services/git-academy-sandbox) 
repository where you can practice using Git in a contained environment. 

You can follow through tasks in order or in some cases jump in at specific points 
where you feel you need to target your learning. A logbook is provided within the 
[git-academy-sandbox](https://github.com/dfe-analytical-services/git-academy-sandbox)
repo. The logbook is to be used alongside this guide to record your progress and practice 
making and recording changes.

:::: {.callout-note}
This isn't aimed at being a comprehensive reference guide. If you need more extensive
reference material for using Git in the DfE, then we recommend looking through
the 
[Azure DevOps for Analysis guide](https://dfe-analytical-services.github.io/azure-devops-for-analysis/).
::::

If at any point in this tutorial you're unsure of any terminology, there is a 
[Glossary](https://dfe-analytical-services.github.io/git-academy/glossary.html)
that contains all of the command words as well as a short description on what
they are and why they are used.