---
title: "Prerequisites"
---

## Git

Download Git from the [Git website downloads page](https://git-scm.com/downloads).
Click the "Download for..." button in the monitor image and this will download 
the install script.

::: {.callout-tip}
The install script asks lots of questions, but you're generally fine to accept 
the defaults on all of these. The main one to watch out for is the default text
editor, which Git sets to Vim. We strongly recommend changing this to Notepad or 
Notepad++ as Vim is very user-unfriendly for the average user.
:::

## GitHub Account

You'll need a GitHub account to work through the examples used with our 
[git-academy-sandbox](https://github.com/dfe-analytical-services/git-academy-sandbox) 
repository. Create an account from the [GitHub homepage](https://github.com/).

Once you've set up an account, [e-mail us](mailto:statistics.development@education.gov.uk)
with your GitHub username and ask to be added to the [Git Academy users](https://github.com/orgs/dfe-analytical-services/teams/git-academy-users) 
team on [dfe-analytical services](https://github.com/dfe-analytical-services).

## Running Git commands

There are a few options for running Git commands once you've installed Git. The
panels below give the most commonly used options that we recommend for working 
through Git Academy.

::: panel-tabset
### IDE Git integration

Most modern IDEs (e.g. **VS Code**, **R-Studio**, **PyCharm**) provide some level of 
Git integration. IDEs often offer a more limited range of Git commands than Git 
Bash and GitHub Desktop, but work well for basic Git workflows (such as cloning,
tracking changes, creating branches and syncing with your remote repository) and 
provide enough functionality to follow most of Git Academy without you needing 
to resort to typing commands into Git Bash.

### (Git) Bash

Bash is a terminal prompt that you can use to run Git commands. A version of the 
Bash terminal (called Git Bash) comes with Git, so you'll have it as soon as you've 
installed Git. It gives you access to all Git commands as well as other Bash commands
for file management etc (such as creating files, navigating through your folders, 
making directories, removing files and many, many other things).

### GitHub Desktop

If writing commands into a terminal isn't your thing, then a good 
(language-agnostic) alternative to Git Bash is to use the GitHub Desktop 
application. This can be downloaded from GitHub and provides access to a wide 
range of Git commands, whilst providing user-friendly views of the tracking 
status and changes of your files.
:::

::: {.callout-note}
There is no single preferred option for running Git commands. Whichever option 
you find works best for you is fine to use, whether it's command line based or
a graphical user interface. Some will offer additional functionality, but all 
shuould provide enough functionality for day-to-day tasks.
:::


## Text editor or IDE

We've tried to keep Git Academy software-agnostic as much as possible, so you
should be able to work through most of the material using any text editor or 
IDE. The main files you'll need to edit will contain markdown, which you can 
edit in any of the following (some of which also provide Git integration).

::: panel-tabset
### Windows Notepad

Windows Notepad and Notepad++ are good to use if you don't have a preferred 
language that you'd usually work in such as R or Python. There's no Git 
integration though, so you'll need to use Git Bash or GitHub Desktop to run 
Git commands.

### VS Code

VS Code is a flexible IDE usable with a range of languages and is available for 
use on DfE systems on request. It provides Git integration along with markdown 
file rendering (shortcut: Ctrl+K V), so is a great option for working through 
Git Academy.

### R-Studio

R-Studio is an R IDE and is available from the DfE Software Centre in Windows. 
It provides Git integration along with markdown file rendering, so is a great 
option for working through Git Academy.

### PyCharm

PyCharm Community Edition is a Python IDE and is available from the DfE Software 
Centre. It provides Git integration along with markdown file rendering, so is 
a great option for working through Git Academy.
:::

